---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lsf-rc-clusterbind
  namespace: @_NAMESPACE_@
subjects:
  - kind: ServiceAccount
    name: @_SA_NAME_@
    namespace: @_NAMESPACE_@
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lsf-rc-clusterrole
